# 專案相關設定
cheng:
  # 名稱
  name: CoolApps
  # 版本
  version: 1.2.3
  # 版權年份
  copyrightYear: 2025
  # 檔案路徑 - 由環境特定設定檔案設定 (application-local.yml 或 application-prod.yml)
  # profile: 路徑將從 application-local.yml 或 application-prod.yml 中取得
  # 取得ip位址開關
  addressEnabled: true
  # 驗證碼類型 math 數字計算 char 字元驗證
  captchaType: math

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:${JASYPT_PASSWORD:}}

# 開發環境設定
server:
  # 伺服器的HTTP埠號，預設為8080
  port: ${PORT:8080}
  servlet:
    # 應用程式的存取路徑
    context-path: /
  tomcat:
    # tomcat的URI編碼
    uri-encoding: UTF-8
    # 連線數滿後的排隊數，預設為100
    accept-count: 1000
    threads:
      # Tomcat最大執行緒數，預設為200
      max: 800
      # Tomcat啟動初始化的執行緒數，預設值10
      min-spare: 100

# 日誌設定
logging:
  level:
    com.cheng: debug
    org.springframework: warn

# 使用者設定
user:
  password:
    # 密碼最大錯誤次數
    maxRetryCount: 3
    # 密碼鎖定時間（預設10分鐘）
    lockTime: 10

# Spring設定
spring:
  # 資源資訊
  messages:
    # 國際化資源檔案路徑
    basename: i18n/messages
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  # 文件上傳
  servlet:
    multipart:
      # 單一檔案大小
      max-file-size: 10MB
      # 設定總上傳的檔案大小
      max-request-size: 20MB
  # 服務模組
  devtools:
    restart:
      # 熱部署開關
      enabled: true

# token設定
token:
  # 令牌自定義標識
  header: Authorization
  # 令牌密鑰
  secret: ENC(Xmcu0N3coRAuG7dbOj6S55XpoFiaNCfdVNP7A30IFt9qPjWt/ZMhPOz19E5Uzf1JLK5gAO5xmvqTkcK9E9A4fQ==)
  # 令牌有效期（預設30分鐘）
  expireTime: 30

# MyBatis設定
mybatis:
  # 搜尋指定包別名
  typeAliasesPackage: com.cheng.**.domain
  # 設定mapper的掃描，找到所有的mapper.xml映射檔案
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 載入全域的設定檔案
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分頁套件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Springdoc設定
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
  group-configs:
    - group: 'default'
      display-name: '測試模組'
      paths-to-match: '/**'
      packages-to-scan: com.cheng.web.controller.tool

# 防盜鏈設定
referer:
  # 防盜鏈開關
  enabled: false
  # 允許的網域列表
  allowed-domains: localhost,127.0.0.1,cheng.vip,www.cheng.vip

# 防止XSS攻擊
xss:
  # 過濾開關
  enabled: true
  # 排除連結（多個以逗號分隔）
  excludes: /system/notice
  # 匹配連結
  urlPatterns: /system/*,/monitor/*,/tool/*
